import { sql } from 'drizzle-orm';
import { integer, timestamp, varchar } from 'drizzle-orm/pg-core';

/**
 * Column conventions shared by every table.
 *
 * Ids are text, not serial: they carry a type prefix (`usr_`, `wkt_`) so a
 * value is self-describing in a log line, and they can be generated by the
 * client before a round trip. Timestamps are always `timestamptz` — a workout
 * completed at 23:30 in Auckland and read at 11:30 in London is the same
 * instant, and storing naive local time makes that unrecoverable.
 */

export const id = (name = 'id') => varchar(name, { length: 40 });

export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
};

/** Money is always an integer count of cents. There is no float money column. */
export const cents = (name: string) => integer(name);

/** Loads are integer grams for the same reason. `102.5 kg` is `102500`. */
export const grams = (name: string) => integer(name);
